// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/63fab6bebdec553e23df506a
###
GET http://localhost:8080/contacts/63fab713bdec553e23df506b
###
GET http://localhost:8080/contacts/63fab64cbdec553e23df5068

// PRODUCTION Deploy
###
GET https://cse341-pmx4.onrender.com/contacts
###
GET https://cse341-pmx4.onrender.com/contacts/63fab6bebdec553e23df506a
###
GET https://cse341-pmx4.onrender.com/contacts/63fab713bdec553e23df506b
###
GET https://cse341-pmx4.onrender.com/contacts/63fab64cbdec553e23df5068